#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * Project-local Bazimya CLI.
 *
 * Works even when the framework is not installed globally:
 *
 *     php bazimya serve
 *     php bazimya make:controller UserController
 */

require __DIR__ . '/vendor/autoload.php';

exit((new Bazimya\Console\Kernel())->run($argv));
